services:
    nodejs_be:
        container_name: one-time-links-be
        image: one-time-links-be
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 3000:3000
        networks:
            - one-time-links-be
        depends_on:
            - redis
    redis:
        container_name: redis
        image: 'bitnami/redis:latest'
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - '6379:6379'
        networks:
          - one-time-links-be
        volumes:
          - redis-data:/bitnami/redis/data
networks:
    one-time-links-be:
      name: one-time-links-be
volumes:
  redis-data:



